"""Public facade for the reusable SLM control package."""

# Registry primitives are intentionally imported first. Populate the default
# registry explicitly before exposing runtime/application objects that consume
# it.
from .core.engine.registry import (
    DEFAULT_REGISTRIES,
    SLMRegistries,
    TargetPresentation,
    TargetPresentationField,
    TargetPresentationFieldKind,
    load_default_registrations as _load_default_registrations,
    register_aberration,
    register_cgh_algorithm,
    register_pattern,
    register_target,
)

_load_default_registrations()

from .application import (
    AutomaticFeedbackState,
    CalibrationAcquisitionAvailability,
    CalibrationMismatchPolicy,
    ConfigLoadOutcome,
    CorrectionMismatch,
    CorrectionMismatchPolicy,
    FeedbackParameterUpdateResult,
    MeasurementDispatcher,
    PreparedConfigLoad,
    PreparedPlaneSelection,
    PreparedSectionLayoutChange,
    SLMCalibrationService,
    SLMConfigurationService,
    SLMControlMode,
    SLMFeedbackService,
    SLMRuntimeFactory,
    SLMSectionLayoutService,
    SLMSession,
    SLMSessionCallbacks,
    StartupPreferencesState,
    StartupRuntime,
    TargetCalibrationState,
)
from .core.calibration import SLMSectionCalibration
from .core.config import (
    SectionConfigLoadResult,
    SLM_CONFIG_SCHEMA_VERSION,
    SLMCompiledFrame,
    SLMConfig,
    SLMConfigLoadReport,
    SLMSectionConfig,
)
from .core.engine.corrections import (
    CorrectionProvider,
    CorrectionSourceInvalidatedError,
    ResolvedCorrections,
)
from .core.engine.device import SLMGeometry,SLMIdentity
from .core.engine.runtime import SLMArtifacts,SLMRuntime
from .core.engine.section import (
    SectionContext,
    SectionGeometry,
    SectionGroupSnapshot,
    SectionLayoutSignature,
    SectionPresentation,
    SectionSplitLayout,
    SectionTopology,
    SectionUpdate,
    SLMSectionRuntime,
    SLMSectionSnapshot,
    SLMSectionState,
    create_split_section_geometries,
    split_layout_signature,
    split_slm_geometry,
    validate_config_section_layout,
    validate_split_section_geometries,
)
from .core.engine.state import GroupTopology
from .core.engine.transition import GroupStateDelta,SectionStateTransition
from .core.measurement import ImageMeasurement
from .setup import (
    SLM_SETUP_FILE_SCHEMA_VERSION,
    SLMDefinition,
    SLMHardwareConfig,
    SLMSectionsDefinition,
    SLMStartupPreferences,
    load_slm_setup_file,
    save_slm_startup_preferences,
)
from .workspace import (
    SLMCalibrationStore,
    SLMConfigInspection,
    SLMConfigMetadata,
    SLMConfigStore,
    SLMCorrectionStore,
    SLMWorkspace,
)

__all__ = [
    "AutomaticFeedbackState",
    "CalibrationAcquisitionAvailability",
    "CalibrationMismatchPolicy",
    "ConfigLoadOutcome",
    "CorrectionMismatch",
    "CorrectionMismatchPolicy",
    "CorrectionProvider",
    "CorrectionSourceInvalidatedError",
    "DEFAULT_REGISTRIES",
    "FeedbackParameterUpdateResult",
    "GroupStateDelta",
    "GroupTopology",
    "ImageMeasurement",
    "MeasurementDispatcher",
    "PreparedConfigLoad",
    "PreparedPlaneSelection",
    "PreparedSectionLayoutChange",
    "ResolvedCorrections",
    "SectionConfigLoadResult",
    "SectionContext",
    "SectionGeometry",
    "SectionGroupSnapshot",
    "SectionLayoutSignature",
    "SectionPresentation",
    "SectionSplitLayout",
    "SectionStateTransition",
    "SectionTopology",
    "SectionUpdate",
    "SLM_CONFIG_SCHEMA_VERSION",
    "SLM_SETUP_FILE_SCHEMA_VERSION",
    "SLMArtifacts",
    "SLMCalibrationService",
    "SLMCalibrationStore",
    "SLMCompiledFrame",
    "SLMConfig",
    "SLMConfigInspection",
    "SLMConfigLoadReport",
    "SLMConfigMetadata",
    "SLMConfigStore",
    "SLMConfigurationService",
    "SLMControlMode",
    "SLMCorrectionStore",
    "SLMFeedbackService",
    "SLMGeometry",
    "SLMHardwareConfig",
    "SLMIdentity",
    "SLMRegistries",
    "SLMRuntime",
    "SLMRuntimeFactory",
    "SLMSectionCalibration",
    "SLMSectionConfig",
    "SLMSectionLayoutService",
    "SLMSectionRuntime",
    "SLMSectionSnapshot",
    "SLMSectionState",
    "SLMSectionsDefinition",
    "SLMSession",
    "SLMSessionCallbacks",
    "SLMDefinition",
    "SLMStartupPreferences",
    "SLMWorkspace",
    "StartupPreferencesState",
    "StartupRuntime",
    "TargetCalibrationState",
    "TargetPresentation",
    "TargetPresentationField",
    "TargetPresentationFieldKind",
    "create_split_section_geometries",
    "load_slm_setup_file",
    "register_aberration",
    "register_cgh_algorithm",
    "register_pattern",
    "register_target",
    "save_slm_startup_preferences",
    "split_layout_signature",
    "split_slm_geometry",
    "validate_config_section_layout",
    "validate_split_section_geometries",
]
